# Reimagine

Our purpose today is to spot things that could help your workflow. The ideas is to reuse what works (for you and others), and ease off what doesn’t work


## What resonates for you from last week?

::: {.callout-caution appearance="minimal" icon="false"}

<!---p.1--->

*Revisit what was top-of-mind from last week. What else has emerged? What patterns, if any, are coming up for you?*


 - Virion remains top of mind
 - task integration remains a challenge 

 
:::

## Where within your workflow seems like a good place to start iterating?

::: {.callout-caution appearance="minimal" icon="false"}

<!---p.2--->

*What stands out about that place? Why are you motivated to focus on this part of your workflow?*

  Integrating task management system is a likely place to start.
- Both currently serve their purpose
- Work is becoming more complex and may outstrip my ability to manage time across both platforms

:::


## Think of a good workflow you’ve seen. What felt good about it? 

::: {.callout-caution appearance="minimal" icon="false"}

<!---p.2--->

*For example, what was it about how it was organized, how different people contributed, how it was communicated? Remember meetings are part of workflows too*

- Trust between team members
- Clear communication about the common objective
- Accountability to team members, with grace and understanding when tasks can't be completed
- Clear definitions of done for tasks
- Prioritization of tasks
- Honest assessments of Level of effort
- Freedom to execute tasks according to expertise
- Understanding among team members that they should lean on each other when necessary


:::

## What have you seen or heard about that has you curious? 

::: {.callout-caution appearance="minimal" icon="false"}

<!---p.2--->

*What are things you’d like to learn or reuse from what you’ve seen? Think from colleagues, talks, and examples online*

  

 obsidian

:::

## What are some of your values?

::: {.callout-caution appearance="minimal" icon="false"}

<!---p.3--->

*Think about something you enjoy doing. What qualities about yourself do you see coming through? What is important to you personally and professionally? How do you want to make people feel?*


  

 

:::

## How do your values show up in your workflow, and how you interact with colleagues?

::: {.callout-caution appearance="minimal" icon="false"}


<!---p.3--->

*How do you show up in your daily life at work? For example, being on time, being organized, interacting with people.*



 

 
  

 
:::


## What would it look like to connect your values more with your workflow?

::: {.callout-caution appearance="minimal" icon="false"}

<!---p.4--->

*Think about that place that seems like a good place to focus. What if you brought what you have seen and want to learn to that place, along with your values? You can draw this*

  

 

  

 

:::